version: '3.9'

services:
  backend:
    build: ./backend
    container_name: corelab-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/corelab_test
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: corelab-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: corelab-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
